### ISSUE TITLE
WP Cron

### ISSUE THREAD

**Issue by joneslloyd** [A5hleyRich/wp-background-processing#16]
Hi there,

Great solution by the way :) Already using it in a plugin I'm developing.

I have two questions:

- Does this rely on WP Cron being enabled on a user's site to work properly?
- Could this somehow act as a WP Cron replacement? I'm trying to think of how I could get it to do that.. If it could, it'd be amazing

Thanks a lot!

**Comment by sfgarza** [comment]
I think I can answer your first question since I just finished reading through the entire source code.

WP Cron doesn't have to be enabled if you're only using the `WP_Async_Request` class to push a single task to the background. But if you're using the `WP_Background_Process` class to process a queue of items in the background then having the Wordpress Cron enabled is necessary since the class uses it to schedule a "Health Check" to see if the process is still running and restart it if something went wrong ( Memory Limit was exceeded or the process timed out ).

**Comment by joneslloyd** [comment]
Hi @sfgarza - Thanks for this information - Interesting to know!

**Comment by arobbins** [comment]
> I think I can answer your first question since I just finished reading through the entire source code.
> 
> WP Cron doesn't have to be enabled if you're only using the `WP_Async_Request` class to push a single task to the background. But if you're using the `WP_Background_Process` class to process a queue of items in the background then having the Wordpress Cron enabled is necessary since the class uses it to schedule a "Health Check" to see if the process is still running and restart it if something went wrong ( Memory Limit was exceeded or the process timed out ).

Just realized this is why my plugin hasn't been working on installs using GoDaddys Managed WordPress hosting. They turn WP Cron off by default!
