### ISSUE TITLE
WordPress database error Got a packet bigger than 'max_allowed_packet' bytes

### ISSUE THREAD

**Issue by marcofacheris** [A5hleyRich/wp-background-processing#60]
Hi,

`WordPress database error Got a packet bigger than 'max_allowed_packet' bytes`

I ran into this error when working with a huge amount of data (like a 20MB JSON of data).
Since the `save()` function saves all the `$data` in a single row of the `wp_options` table, if the data is actually a lot of data, it throws this error.

I solved it by following @No3x advice in #7 and doing the following:

```
foreach($jsonData as $data) {
    $this->wp_background_processing_instance->push_to_queue($data);
    $this->wp_background_processing_instance->save();
}
$this->wp_background_processing_instance->dispatch();
```
I put the `dispatch` function outside the loop, looks cleaner.

Then in my `wp_background_processing` class:

```
public function save() {
    parent::save();
    $this->data = [];
    return $this;
}
```

As stated in the referenced issue, this creates an option in the database for each item in the queue, and maybe this is not ideal. But at least this prevent the database error.

Is there a better way to prevent this?

**Comment by No3x** [comment]
Hi @marcofacheris 

Your problem has an other nature as the one in #7 - it was: 
> what happens if I add data to a task that might already process (asynchronous, event like)?

Your Problem is: 
> I have full control about what data I save and I don't need to add data after dispatch was called. (synchronous, collection). 

Do you understand the difference here?

I think my idea was just to chunk the data (in your case $jsonData). I'm not sure if this is possible because I guess you have a very big json object that is kind of "atomic" at the moment.

I guess you have to change your task so that it can work with subsets of the json. Maybe it is easy to chunk because the json contains just a collection that you can split into two chunks and the problem is solved.

**Comment by marcofacheris** [comment]
Hi @No3x 

yes, I understand the difference, I referenced #7 just because I used your fix to fix my issue.

I know I could split my data in chunks, but I'm afraid it would affect the impact on the server resource-wise, as maybe timeout problems can occur?

Thanks for your reply.

**Comment by marcofacheris** [comment]
Hi again @No3x 

As I am working with a collection, I managed to split my data in chunks. This should prevent the `Got a packet bigger than` error, and is better than having an option in the database for each batch.

Thanks
